addEventListener('fetch', event => {
    event.respondWith(blockPops(event.request))
  })
  
  /*
  Create a list of PoPs in the Cloudflare network
  which should not respond to requests, serving a
  HTTP 403 instead.
  */
  
  /*
  Map of PoPs which should not respond
  This example allows only EU countries
  */
  const pops = new Map([  
    ['ADL', false], //Adelaide, AU (OC)
    ['AKL', false], //Auckland, NZ (OC)
    ['AMM', false], //Amman, JO (ME)
    ['AMS', true], //Amsterdam, NL (WEUR)
    ['ARI', false], //Arica, CL (SAM)
    ['ARN', true], //Stockholm, SE (EEUR)
    ['ASH', false], //Ashburn, VA, US (NAM)
    ['ASU', false], //Asunción, PY (SAM)
    ['ATH', true], //Athens, GR (EEUR)
    ['ATL', false], //Atlanta, GA, US (ENAM)
    ['AUS', false], //Austin, TX, US (WNAM)
    ['BAH', false], //Manama, BH (ME)
    ['BCN', true], //Barcelona, ES (WEUR)
    ['BEG', true], //Belgrade, RS (EEUR)
    ['BEY', false], //Beirut, LB (ME)
    ['BGW', false], //Baghdad, IQ (ME)
    ['BKK', false], //Bangkok, TH (APAC)
    ['BLR', false], //Bangalore, IN (APAC)
    ['BNA', false], //Nashville, TN, US (ENAM)
    ['BNE', false], //Brisbane, AU (OC)
    ['BOG', false], //Bogotá, CO (SAM)
    ['BOM', false], //Mumbai, IN (APAC)
    ['BOS', false], //Boston, MA, US (ENAM)
    ['BRU', true], //Brussels, BE (WEUR)
    ['BUD', true], //Budapest, HU (EEUR)
    ['BUF', false], //Buffalo, NY, US (ENAM)
    ['BWN', false], //Bandar Seri Begawan, BN (APAC)
    ['CAI', false], //Cairo, EG (AFR)
    ['CAN', false], //Guangzhou, CN (CHINA)
    ['CCU', false], //Kolkata, IN (APAC)
    ['CDG', true], //Paris, FR (WEUR)
    ['CEB', false], //Cebu, PH (APAC)
    ['CGK', false], //Jakarta, ID (APAC)
    ['CGO', false], //Zhengzhou, CN (CHINA)
    ['CGP', false], //Chittagong, BD (APAC)
    ['CKG', false], //Chongqing, CN (CHINA)
    ['CLT', false], //Charlotte, NC, US (ENAM)
    ['CMB', false], //Colombo, LK (APAC)
    ['CMH', false], //Columbus, OH, US (ENAM)
    ['CMN', false], //Casablanca, MA (AFR)
    ['COR', false], //Córdoba, AR (SAM)
    ['CPH', true], //Copenhagen, DK (EEUR)
    ['CPT', false], //Cape Town, ZA (AFR)
    ['CSX', false], //Zhuzhou, CN (CHINA)
    ['CTU', false], //Chengdu, CN (CHINA)
    ['CUR', false], //Willemstad, CW (SAM)
    ['CWB', false], //Curitiba, BR (SAM)
    ['DAC', false], //Dhaka, BD (APAC)
    ['DAR', false], //Dar Es Salaam, TZ (AFR)
    ['DEL', false], //New Delhi, IN (APAC)
    ['DEN', false], //Denver, CO, US (WNAM)
    ['DFW', false], //Dallas, TX, US (WNAM)
    ['DKR', false], //Dakar, SN (AFR)
    ['DLC', false], //Dalian, CN (CHINA)
    ['DME', true], //Moscow, RU (EEUR)
    ['DOH', false], //Doha, QA (ME)
    ['DTW', false], //Detroit, MI, US (ENAM)
    ['DUB', true], //Dublin, IE (WEUR)
    ['DUR', false], //Durban, ZA (AFR)
    ['DUS', true], //Dusseldorf, DE (WEUR)
    ['DXB', false], //Dubai, AE (ME)
    ['EDI', true], //Edinburgh, GB (WEUR)
    ['EVN', false], //Yerevan, AM (ME)
    ['EWR', false], //Newark, NJ, US (ENAM)
    ['EZE', false], //Buenos Aires, AR (SAM)
    ['FCO', true], //Rome, IT (EEUR)
    ['FOC', false], //Fuzhou, CN (CHINA)
    ['FOR', false], //Fortaleza, BR (SAM)
    ['FRA', true], //Frankfurt, DE (EEUR)
    ['FUO', false], //Foshan, CN (CHINA)
    ['GIG', false], //Rio De Janeiro, BR (SAM)
    ['GND', false], //St. George'S, GD (SAM)
    ['GOT', true], //Gothenburg, SE (EEUR)
    ['GRU', false], //São Paulo, BR (SAM)
    ['GUA', false], //Guatemala City, GT (WNAM)
    ['GUM', false], //Hagatna, GU (APAC)
    ['GVA', true], //Geneva, CH (WEUR)
    ['GYD', false], //Baku, AZ (ME)
    ['HAM', true], //Hamburg, DE (EEUR)
    ['HAN', false], //Hanoi, VN (APAC)
    ['HEL', true], //Helsinki, FI (EEUR)
    ['HGH', false], //Hangzhou, CN (CHINA)
    ['HKG', false], //Hong Kong, HK (APAC)
    ['HNL', false], //Honolulu, HI, US (WNAM)
    ['HNY', false], //Hengyang, CN (CHINA)
    ['HRE', false], //Harare, ZW (AFR)
    ['HYD', false], //Hyderabad, IN (APAC)
    ['IAD', false], //Ashburn, VA, US (ENAM)
    ['IAH', false], //Houston, TX, US (ENAM)
    ['ICN', false], //Seoul, KR (APAC)
    ['IND', false], //Indianapolis, IN, US (ENAM)
    ['ISB', false], //Islamabad, PK (APAC)
    ['IST', true], //Istanbul, TR (EEUR)
    ['JAX', false], //Jacksonville, FL, US (ENAM)
    ['JHB', false], //Johor Bahru, MY (APAC)
    ['JIB', false], //Djibouti, DJ (AFR)
    ['JNB', false], //Johannesburg, ZA (AFR)
    ['JSR', false], //Jashore, BD (APAC)
    ['JXG', false], //Jiaxing, CN (CHINA)
    ['KBP', true], //Kyiv, UA (EEUR)
    ['KEF', true], //Reykjavík, IS (WEUR)
    ['KGL', false], //Kigali, RW (AFR)
    ['KHI', false], //Karachi, PK (APAC)
    ['KIV', true], //Chișinău, MD (EEUR)
    ['KIX', false], //Osaka, JP (APAC)
    ['KTM', false], //Kathmandu, NP (APAC)
    ['KUL', false], //Kuala Lumpur, MY (APAC)
    ['KWI', false], //Kuwait City, KW (ME)
    ['LAD', false], //Luanda, AO (AFR)
    ['LAS', false], //Las Vegas, NV, US (WNAM)
    ['LAX', false], //Los Angeles, CA, US (WNAM)
    ['LCA', true], //Nicosia, CY (EEUR)
    ['LED', true], //Saint Petersburg, RU (EEUR)
    ['LHE', false], //Lahore, PK (APAC)
    ['LHR', true], //London, GB (WEUR)
    ['LHW', false], //Lanzhou, CN (CHINA)
    ['LIM', false], //Lima, PE (SAM)
    ['LIS', true], //Lisbon, PT (WEUR)
    ['LOS', false], //Lagos, NG (AFR)
    ['LUX', true], //Luxembourg City, LU (WEUR)
    ['LYA', false], //Luoyang, CN (CHINA)
    ['MAA', false], //Chennai, IN (APAC)
    ['MAD', true], //Madrid, ES (WEUR)
    ['MAN', true], //Manchester, GB (WEUR)
    ['MBA', false], //Mombasa, KE (AFR)
    ['MCI', false], //Kansas City, MO, US (ENAM)
    ['MCT', false], //Muscat, OM (ME)
    ['MDE', false], //Medellin, CO (SAM)
    ['MEL', false], //Melbourne, AU (OC)
    ['MEM', false], //Memphis, TN, US (ENAM)
    ['MEX', false], //Mexico City, MX (WNAM)
    ['MFE', false], //Mcallen, TX, US (ENAM)
    ['MFM', false], //Macau, MO (APAC)
    ['MGM', false], //Montgomery, AL, US (ENAM)
    ['MIA', false], //Miami, FL, US (ENAM)
    ['MLE', false], //Male, MV (APAC)
    ['MNL', false], //Manila, PH (APAC)
    ['MPM', false], //Maputo, MZ (AFR)
    ['MRS', true], //Marseille, FR (WEUR)
    ['MRU', false], //Port Louis, MU (AFR)
    ['MSP', false], //Minneapolis, MN, US (ENAM)
    ['MUC', true], //Munich, DE (WEUR)
    ['MXP', true], //Milan, IT (EEUR)
    ['NAG', false], //Nagpur, IN (APAC)
    ['NAY', false], //Langfang, CN (CHINA)
    ['NBG', false], //Ningbo, CN (CHINA)
    ['NBO', false], //Nairobi, KE (AFR)
    ['NNG', false], //Nanning, CN (CHINA)
    ['NOU', false], //Noumea, NC (OC)
    ['NQN', false], //Neuquen, AR (SAM)
    ['NRT', false], //Tokyo, JP (APAC)
    ['OMA', false], //Omaha, NE, US (ENAM)
    ['ORD', false], //Chicago, IL, US (ENAM)
    ['ORD', false], //Chicago, IL, US (NAM)
    ['ORF', false], //Norfolk, VA, US (ENAM)
    ['ORK', true], //Cork, IE (WEUR)
    ['OSL', true], //Oslo, NO (EEUR)
    ['OTP', true], //Bucharest, RO (EEUR)
    ['PAP', false], //Port-Au-Prince, HT (WNAM)
    ['PBH', false], //Thimphu, BT (APAC)
    ['PBM', false], //Paramaribo, SR (SAM)
    ['PDX', false], //Portland, OR, US (WNAM)
    ['PER', false], //Perth, AU (OC)
    ['PHL', false], //Philadelphia, PA, US (ENAM)
    ['PHX', false], //Phoenix, AZ, US (WNAM)
    ['PIT', false], //Pittsburgh, PA, US (ENAM)
    ['PNH', false], //Phnom Penh, KH (APAC)
    ['POA', false], //Porto Alegre, BR (SAM)
    ['PRG', true], //Prague, CZ (EEUR)
    ['PTY', false], //Panama City, PA (SAM)
    ['PVG', false], //Shanghai, CN (CHINA)
    ['QRO', false], //Queretaro, MX (WNAM)
    ['RGN', false], //Yangon, MM (APAC)
    ['RIC', false], //Richmond, VA, US (ENAM)
    ['RIX', true], //Riga, LV (EEUR)
    ['ROB', false], //Monrovia, LR (AFR)
    ['RUH', false], //Riyadh, SA (ME)
    ['RUN', false], //Saint-Denis, RE (AFR)
    ['SAN', false], //San Diego, CA, US (WNAM)
    ['SCL', false], //Santiago, CL (SAM)
    ['SEA', false], //Seattle, WA, US (WNAM)
    ['SFO', false], //San Francisco, CA, US (CHINA)
    ['SFO', false], //San Francisco, CA, US (WNAM)
    ['SGN', false], //Ho Chi Minh City, VN (APAC)
    ['SHA', false], //Shanghai, CN (CHINA)
    ['SHE', false], //Shenyang, CN (CHINA)
    ['SIN', false], //Singapore, SG (APAC)
    ['SJC', false], //San Jose, CA, US (WNAM)
    ['SJO', false], //San José, CR (WNAM)
    ['SJW', false], //Shijiazhuang, CN (CHINA)
    ['SKG', true], //Thessaloniki, GR (EEUR)
    ['SLC', false], //Salt Lake City, UT, US (WNAM)
    ['SMF', false], //Sacramento, CA, US (WNAM)
    ['SOF', true], //Sofia, BG (EEUR)
    ['SSA', false], //Salvador, BR (SAM)
    ['STL', false], //St. Louis, MO, US (WNAM)
    ['SYD', false], //Sydney, AU (OC)
    ['SZV', false], //Suzhou, CN (CHINA)
    ['SZX', false], //Dongguan, CN (CHINA)
    ['TAO', false], //Tsingtao, CN (CHINA)
    ['TBS', true], //Tbilisi, GE (EEUR)
    ['TGU', false], //Tegucigalpa, HN (SAM)
    ['TKO', false], //Tokyo, JP (APAC)
    ['TLH', false], //Tallahassee, FL, US (ENAM)
    ['TLL', true], //Tallinn, EE (EEUR)
    ['TLV', false], //Tel Aviv, IL (ME)
    ['TNA', false], //Jinan, CN (CHINA)
    ['TNR', false], //Antananarivo, MG (AFR)
    ['TPA', false], //Tampa, FL, US (ENAM)
    ['TPE', false], //Taipei, TW (APAC)
    ['TSN', false], //Tianjin, CN (CHINA)
    ['TUN', false], //Tunis, TN (AFR)
    ['TXL', true], //Berlin, DE (EEUR)
    ['UIO', false], //Quito, EC (SAM)
    ['ULN', false], //Ulaanbaatar, MN (APAC)
    ['VIE', true], //Vienna, AT (EEUR)
    ['VNO', true], //Vilnius, LT (EEUR)
    ['VTE', false], //Vientiane, LA (APAC)
    ['WAW', true], //Warsaw, PL (EEUR)
    ['WUH', false], //Wuhan, CN (CHINA)
    ['WUX', false], //Wuxi, CN (CHINA)
    ['XIY', false], //Xian, CN (CHINA)
    ['YOW', false], //Ottawa, ON, CA (ENAM)
    ['YTY', false], //Yangzhou, CN (CHINA)
    ['YUL', false], //Montreal, QC, CA (ENAM)
    ['YVR', false], //Vancouver, BC, CA (WNAM)
    ['YWG', false], //Winnipeg, MB, CA (ENAM)
    ['YXE', false], //Saskatoon, SK, CA (WNAM)
    ['YYC', false], //Calgary, AB, CA (WNAM)
    ['YYZ', false], //Toronto, ON, CA (ENAM)
    ['ZAG', true], //Zagreb, HR (EEUR)
    ['ZDM', false], //Ramallah, PS (ME)
    ['ZRH', true] //Zurich, CH (EEUR)
  ])
  
  async function blockPops(request) {
  
    //Get PoP ID from cf blob
    let popID = request.cf.colo
  
    //Get bool from pops map
    let pop = pops.get(popID)
  
    //Only try to block if cf blob and map entry exist
    if (popID != null && pop != null){
  
      //Return HTTP 403 instead of the response if entry exists in map
      if (pop == false){
        return new Response('Sorry, this page is not available in your area: ' + popID,
          { status: 403, statusText: 'Forbidden' })
      }
    }
  
    //Catch-all of original response
    return await fetch(request)
  }